-- ============================================================
-- Migration 18: orphaned v1 timetables table (Step 12 cleanliness) — CLOSED
-- ============================================================
-- Background: `public.timetables` was the original v1 timetable table,
-- later superseded by `timetable_slots` (migration-academy-suite-v2.sql
-- explicitly says "timetables table is left untouched; the app now uses
-- timetable_slots"). Confirmed unreferenced anywhere in src/.
--
-- Verified 2026-09-14 in the Supabase SQL Editor:
--   select count(*) from public.timetables;
--   -> ERROR: 42P01: relation "public.timetables" does not exist
--
-- The table was never actually created in production (or was already
-- removed earlier) -- there is nothing to drop here. No DROP TABLE was
-- run against production for this migration.
--
-- Action taken instead: removed the `timetables` CREATE TABLE / RLS /
-- policy definitions from supabase/schema.sql (the fresh-install
-- snapshot), so a new environment set up from schema.sql doesn't
-- recreate this dead table. supabase/migration-academy-suite.sql (the
-- old standalone migration) is left as historical record with a note --
-- it should not be run against this project any more.
--
-- This migration file is intentionally left in place (renumbered
-- migrations would be more disruptive than useful) as a record of the
-- investigation. No SQL needs to be run for it.
